use serde::{Deserialize, Serialize};
use ts_rs::TS;

pub const CURRENT_SCHEMA_VERSION: u32 = 6;

pub const DEFAULT_UNITY_IGNORE_RULES: &[&str] = &[
    "/[Ll]ibrary/*",
    "!/[Ll]ibrary/metadata",
    "!/[Ll]ibrary/assetDatabase3",
    "/[Tt]emp/",
    "/[Oo]bj/",
    "/[Bb]uild/",
    "/[Bb]uilds/",
    "/[Ll]ogs/",
    "/[Uu]ser[Ss]ettings/",
    "*.log",
    "",
    "# By default Unity supports Blender asset imports; backup files do not need version control.",
    "*.blend1",
    "*.blend1.meta",
    "",
    "# MemoryCaptures can get excessive in size and may contain sensitive data.",
    "/[Mm]emoryCaptures/",
    "# Recordings can get excessive in size.",
    "/[Rr]ecordings/",
    "",
    "# Asset meta data should only be ignored when the corresponding asset is also ignored.",
    "!/[Aa]ssets/**/*.meta",
    "",
    "# Uncomment this line if you wish to ignore the asset store tools plugin.",
    "# /[Aa]ssets/AssetStoreTools*",
    "",
    "# Autogenerated JetBrains Rider plugin.",
    "/[Aa]ssets/Plugins/Editor/JetBrains*",
    "# JetBrains Rider personal-layer settings.",
    "*.DotSettings.user",
    "",
    "# Visual Studio cache directory.",
    ".vs/",
    "# Gradle cache directory.",
    ".gradle/",
    "",
    "# Autogenerated VS/MD/Consulo solution and project files.",
    "ExportedObj/",
    ".consulo/",
    "*.csproj",
    "*.unityproj",
    "*.sln",
    "*.slnx",
    "*.suo",
    "*.tmp",
    "*.user",
    "*.userprefs",
    "*.pidb",
    "*.booproj",
    "*.svd",
    "*.pdb",
    "*.mdb",
    "*.opendb",
    "*.VC.db",
    "",
    "# Unity generated metadata and crash-report files.",
    "*.pidb.meta",
    "*.pdb.meta",
    "*.mdb.meta",
    "sysinfo.txt",
    "mono_crash.*",
    "",
    "# Builds.",
    "*.apk",
    "*.aab",
    "*.unitypackage",
    "*.unitypackage.meta",
    "*.app",
    "",
    "# Crashlytics generated file.",
    "Assets/StreamingAssets/crashlytics-build.properties",
    "",
    "# Packed Addressables and generated Addressables files.",
    "/[Aa]ssets/[Aa]ddressable[Aa]ssets[Dd]ata/*/*.bin*",
    "/[Aa]ssets/AddressableAssetsData/link.xml*",
    "/[Aa]ssets/Addressables_Temp*",
    "",
    "# Temporary auto-generated Android Assets.",
    "/[Aa]ssets/[Ss]treamingAssets/aa.meta",
    "/[Aa]ssets/[Ss]treamingAssets/aa/*",
    "",
    "# Visual Scripting generated files.",
    "/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db",
    "/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db.meta",
    "/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers",
    "/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers.meta",
    "",
    "# Auto-generated scenes and cache.",
    "/[Aa]ssets/[Ii]nit[Tt]est[Ss]cene*.unity*",
    "/[Aa]ssets/[Ss]ceneDependencyCache*",
];
pub const DEFAULT_VPM_EXCLUDE_IGNORE_RULES: &[&str] =
    &["com.vrchat.*", "!com.vrchat.core.vpm-resolver/"];

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, TS, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum VpmTrackingPolicy {
    #[default]
    ExcludePackages,
    IncludePackages,
}

/// `.gitignore` が未作成、または不足ルールを持つ project に適用する設定値。
/// settings.json を直接編集でき、Vsedi は次回の初期化 preview 時に読み直す。
#[derive(Debug, Clone, Serialize, Deserialize, TS, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct IgnoreTemplateSettings {
    pub unity_rules: Vec<String>,
    pub vpm_exclude_rules: Vec<String>,
}

impl Default for IgnoreTemplateSettings {
    fn default() -> Self {
        Self {
            unity_rules: DEFAULT_UNITY_IGNORE_RULES
                .iter()
                .map(|rule| (*rule).to_owned())
                .collect(),
            vpm_exclude_rules: DEFAULT_VPM_EXCLUDE_IGNORE_RULES
                .iter()
                .map(|rule| (*rule).to_owned())
                .collect(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, TS, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecentProject {
    pub path: String,
    pub last_opened_at: Option<String>,
    #[serde(default)]
    pub tags: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecentProjectStatus {
    pub path: String,
    pub last_opened_at: Option<String>,
    pub tags: Vec<String>,
    pub exists: bool,
    pub project_kind: Option<crate::models::diagnostics::ProjectKind>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RepositorySettings {
    pub repository_root: String,
    #[serde(default)]
    pub vpm_tracking_policy_override: Option<VpmTrackingPolicy>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AppSettings {
    pub schema_version: u32,
    #[serde(default)]
    pub onboarding_completed: bool,
    #[serde(default)]
    pub recent_projects: Vec<RecentProject>,
    #[serde(default = "default_log_level")]
    pub log_level: String,
    #[serde(default)]
    pub vpm_tracking_policy: VpmTrackingPolicy,
    #[serde(default)]
    pub ignore_templates: IgnoreTemplateSettings,
    #[serde(default)]
    pub repository_settings: Vec<RepositorySettings>,
}

fn default_log_level() -> String {
    "INFO".to_owned()
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SCHEMA_VERSION,
            onboarding_completed: false,
            recent_projects: Vec::new(),
            log_level: default_log_level(),
            vpm_tracking_policy: VpmTrackingPolicy::default(),
            ignore_templates: IgnoreTemplateSettings::default(),
            repository_settings: Vec::new(),
        }
    }
}
